const express = require("express");
const router = express.Router();
const controllers = require("../../controllers/user");
const wrapper = require("../../helpers/controllerWrappers");
const auth = require("../../middlewares/authMiddleware");
const controller = require("../../controllers/auth");
// router.use(auth);
router.post("/", wrapper(auth), controllers.addContact);
router.get("/contact", wrapper(auth), controllers.getListContact);
router.get("/current", wrapper(auth), controllers.getInfo);
router.post("/logout", wrapper(auth), controller.logout);
module.exports = router;
